# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/sample1"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/sample2"
    schedule:
      interval: "monthly"
